START_SACRIFICING_YEAR = 20
LOW_ENERGY_LEVEL = -9
NORMAL_ENERGY_LEVEL = 0
MAX_ENERGY_LEVEL = 10
EXHAUSTED_ENERGY_LEVEL = -10

# to sacrifice members
NUM_TURNS_TO_WAIT_BEFORE_SACRIFICING = 4

# to determine acceptable energy level
TURNS_TO_LOOK_BACK = 4